export const videos = [
    {
        link: 'https://www.youtube.com/watch?v=QFaFIcGhPoM&list=PLC3y8-rFHvwgg3vaYJgHGnModB54rxOk3',
        image: 'https://reactjs.org/logo-og.png',
        avatar: 'https://material-ui.com/static/images/avatar/1.jpg',
        title: "React JS Turorial - 1 - Introduction",
        channelName: "Codevolution",
        viewCount: "67 K",
        time: "2 weeks ago",
    },
    {
        link: 'https://www.youtube.com/watch?v=QFaFIcGhPoM&list=PLC3y8-rFHvwgg3vaYJgHGnModB54rxOk3',
        image: 'https://reactjs.org/logo-og.png',
        avatar: 'https://material-ui.com/static/images/avatar/2.jpg',
        title: "React JS Turorial - 2 - Hello World",
        channelName: "Codevolution",
        viewCount: "67 K",
        time: "2 weeks ago",
    },
    {
        link: 'https://www.youtube.com/watch?v=QFaFIcGhPoM&list=PLC3y8-rFHvwgg3vaYJgHGnModB54rxOk3',
        image: 'https://reactjs.org/logo-og.png',
        avatar: 'https://material-ui.com/static/images/avatar/3.jpg',
        title: "React JS Turorial - 1 - Folder Structure",
        channelName: "Codevolution",
        viewCount: "67 K",
        time: "2 weeks ago",
    },
    {
        link: 'https://www.youtube.com/watch?v=QFaFIcGhPoM&list=PLC3y8-rFHvwgg3vaYJgHGnModB54rxOk3',
        image: 'https://reactjs.org/logo-og.png',
        avatar: 'https://material-ui.com/static/images/avatar/1.jpg',
        title: "React JS Turorial - 3 - Components",
        channelName: "Codevolution",
        viewCount: "67 K",
        time: "2 weeks ago",
    },
    {
        link: 'https://www.youtube.com/watch?v=QFaFIcGhPoM&list=PLC3y8-rFHvwgg3vaYJgHGnModB54rxOk3',
        image: 'https://reactjs.org/logo-og.png',
        avatar: 'https://material-ui.com/static/images/avatar/2.jpg',
        title: "React JS Turorial - 4 - Functional",
        channelName: "Codevolution",
        viewCount: "67 K",
        time: "2 weeks ago",
    },
    {
        link: 'https://www.youtube.com/watch?v=QFaFIcGhPoM&list=PLC3y8-rFHvwgg3vaYJgHGnModB54rxOk3',
        image: 'https://reactjs.org/logo-og.png',
        avatar: 'https://material-ui.com/static/images/avatar/3.jpg',
        title: "React JS Turorial - 5 - Class",
        channelName: "Codevolution",
        viewCount: "67 K",
        time: "2 weeks ago",
    },
    {
        link: 'https://www.youtube.com/watch?v=QFaFIcGhPoM&list=PLC3y8-rFHvwgg3vaYJgHGnModB54rxOk3',
        image: 'https://reactjs.org/logo-og.png',
        avatar: 'https://material-ui.com/static/images/avatar/1.jpg',
        title: "React JS Turorial - 6 - JSX",
        channelName: "Codevolution",
        viewCount: "67 K",
        time: "2 weeks ago",
    },
    {
        link: 'https://www.youtube.com/watch?v=QFaFIcGhPoM&list=PLC3y8-rFHvwgg3vaYJgHGnModB54rxOk3',
        image: 'https://reactjs.org/logo-og.png',
        avatar: 'https://material-ui.com/static/images/avatar/2.jpg',
        title: "React JS Turorial - 7 - Props",
        channelName: "Codevolution",
        viewCount: "67 K",
        time: "2 weeks ago",
    },
    {
        link: 'https://www.youtube.com/watch?v=QFaFIcGhPoM&list=PLC3y8-rFHvwgg3vaYJgHGnModB54rxOk3',
        image: 'https://reactjs.org/logo-og.png',
        avatar: 'https://material-ui.com/static/images/avatar/3.jpg',
        title: "React JS Turorial - 8 - State",
        channelName: "Codevolution",
        viewCount: "67 K",
        time: "2 weeks ago",
    },
];